# Generated by Django 5.1.6 on 2025-02-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('place_for', models.DecimalField(decimal_places=1, max_digits=2)),
                ('specifications', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('customers_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number1', models.CharField(max_length=30)),
                ('phone_number2', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('social_account1', models.CharField(max_length=100)),
                ('social_account2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DishesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('specifications', models.CharField(max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('portion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dishesmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderers_name', models.CharField(max_length=30)),
                ('orderers_phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('dishes', models.ManyToManyField(through='restaurant.OrderDetails', to='restaurant.dishesmenu')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.orders'),
        ),
    ]
