# Generated by Django 5.1.6 on 2025-02-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingplace',
            table='bookingplace',
        ),
    ]
