# Generated by Django 5.1.6 on 2025-02-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_bookingplace_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.dishesmenu'),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
