# Generated by Django 5.1.6 on 2025-02-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_orders_quantity_alter_orders_dishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dishesmenu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.orders')),
            ],
        ),
    ]
