# Generated by Django 4.2.20 on 2025-03-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_dishesmenu_specifications_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesmenu',
            name='specifications',
            field=models.CharField(blank=True, default='No specifications', max_length=30),
        ),
    ]
